# Generated by Django 3.0.8 on 2020-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('mood', models.CharField(max_length=10)),
            ],
        ),
    ]
