# Generated by Django 3.0.8 on 2020-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
